# Generated by Django 6.0.1 on 2026-02-11 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockalert_stockmovement_alter_inventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase from Supplier'), ('sale', 'Sale to Customer'), ('return', 'Customer Return'), ('damage', 'Damage/Spoiled'), ('wastage', 'Wastage'), ('transfer', 'Warehouse Transfer'), ('adjustment', 'Stock Adjustment'), ('opening', 'Opening Stock')], max_length=20),
        ),
    ]
