# Generated by Django 6.0.1 on 2026-02-04 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='warehouse code e.g. WH-001', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('address', models.TextField(help_text='full address of the warehouse')),
                ('city', models.CharField(help_text='city of the warehouse', max_length=100)),
                ('state', models.CharField(help_text='state of the warehouse', max_length=100)),
                ('postal_code', models.CharField(help_text='postal code of the warehouse', max_length=20)),
                ('country', models.CharField(default='Nepal', help_text='country of the warehouse', max_length=100)),
                ('phone', models.CharField(help_text='contact phone number of the warehouse', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_capacity', models.DecimalField(decimal_places=2, help_text='total capacity of the warehouse in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', help_text='current status of the warehouse', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='additional information about the warehouse', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role_in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('zone_type', models.CharField(choices=[('dry', 'Dry Storage'), ('cold', 'Cold Storage'), ('frozen', 'Frozen Storage'), ('ambient', 'Ambient Storage'), ('hazmat', 'Hazardous Material Storage')], default='dry', max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='capacity of the storage zone in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='minimum temperature in Celsius', max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, help_text='maximum temperature in Celsius', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='additional information about the storage zone', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Storage Zone',
                'verbose_name_plural': 'Storage Zones',
                'ordering': ['warehouse', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='unique location code', max_length=50)),
                ('aisle', models.CharField(blank=True, help_text='aisle identifier (e.g. A, B, etc.)', max_length=10, null=True)),
                ('rack', models.CharField(blank=True, help_text='rack identifier (e.g. 1, 2, etc.)', max_length=10, null=True)),
                ('shelf', models.CharField(blank=True, help_text='shelf identifier (e.g. 1, 2, etc.)', max_length=10, null=True)),
                ('bin', models.CharField(blank=True, help_text='bin identifier (e.g. 1, 2, etc.)', max_length=10, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, help_text='maximum weigth capacity in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='additional information about the storage location', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouses.storagezone')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='warehouses__name_add6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouses__code_d781d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagezone',
            unique_together={('warehouse', 'code')},
        ),
    ]
