# Generated by Django 6.0.1 on 2026-02-15 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_shelf_life_product_shelf_life_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('code', models.CharField(help_text='Unique code for the supplier', max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or VAT number', max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. Net 30, COD, Advance Payment', max_length=200, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Maximum amount the supplier is allowed to credit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Good'), (3, '⭐⭐⭐ Average'), (2, '⭐⭐ Below Average'), (1, '⭐ Poor')], default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, help_text='Supplier-specific SKU for the product', max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of the product for the supplier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, help_text='Minimum order quantity for the supplier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.IntegerField(default=0, help_text='Lead time in days for the supplier')),
                ('is_available', models.BooleanField(default=True, help_text='Is the product available for purchase from the supplier')),
                ('is_preferred', models.BooleanField(default=False, help_text='Is the product a preferred choice for the supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Product',
                'verbose_name_plural': 'Supplier Products',
                'ordering': ['supplier', 'product'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('supplier', 'product')},
        ),
    ]
