# Generated by Django 6.0.1 on 2026-02-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shelf_life',
            new_name='shelf_life_days',
        ),
    ]
